# Generated by Django 5.2 on 2025-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
